config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only:[:index, :new, :create, :edit, :update]
  resources :profiles, only:[:index, :new, :create, :edit, :update]
  resources :tops, only:[:index, :new, :create, :edit, :update]
  resources :contacts, only:[:index, :new, :create]
  resources :articles
  root 'tops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/top.rb
class Top < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(created_at: :DESC)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to :action => "index", :id => @article.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    redirect_to action: :index
  end

  private
  def article_params
    params.require(:article).permit(:image, :site_url, :date)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all.order(created_at: :DESC)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.order(created_at: :DESC)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to :action => "index", :id => @product.id
    else
      redirect_to :action => "new"
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :detail, :site_url, :production_period, :image, :github_url, :language)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to :action => "index", :id => @profile.id
    else
      redirect_to :action => "new"
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:name_jp, :name_en, :hobby, :public_relations, :image, :career, :email, :birthday, :instagram_url, :github_url, :strong_point, :language, :framework, :deploy)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @tops = Top.all
  end

  def new
    @top = Top.new
  end

  def create
    @top = Top.new(top_params)
    if @top.save
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end 

  def edit
    @top = Top.find(params[:id])
  end

  def update
    @top = Top.find(params[:id])
    if @top.update(top_params)
      redirect_to :action => "index", :id => @top.id
    else
      redirect_to :action => "new"
    end
  end

  private
  def top_params
    params.require(:top).permit(:news, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>
  <%= f.label :画像 %>
  <%= f.file_field :image %>
  <br>
  <%= f.label :URL %>
  <%= f.text_field :site_url,size: 140 %>
  <br>
  <%= f.label :書いた日 %>
  <%= f.text_field :date,size: 140 %>
  <br>
  <%= f.submit %>
  <br>
<% end %>

app/views/articles/index.html.erb
<div>
  <% if user_signed_in? %>
    <% if current_user == @user || current_user.admin? %>
      <%= link_to "新規投稿へ", new_article_path %>
    <% end %>
  <% end %>
  <div class="article_title">Articles</div>
  <div class="article">
    <% unless @articles.present? %>
      <div class="no_article">現在技術発信はしていません</div>
    <% end %>
    <% @articles.each do |t| %>
      <div class="article_content">
        <%= link_to t.site_url, target: :_blank do %>
          <%= image_tag t.image_url, class:"article_image" %>
        <% end %>
        <div><%= t.date %></div>
        <% if user_signed_in? %>
          <% if current_user == @user || current_user.admin? %>
          <div class="edit">
            <%= link_to "編集する", edit_article_path(t.id) %>
            <%= link_to "削除する", article_path(t.id), method: :delete %>
          </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <footer>
    <div class="my_link">
      <%= link_to "https://www.instagram.com/bebeko___/", target: :_blank do %>
        <%= image_tag 'instagram.png', class:"image" %>
      <% end %>
      <%= link_to "https://www.facebook.com/ami.osabe.9/", target: :_blank do %>
        <%= image_tag 'facebook.png', class:"image" %>
      <% end %>
      <%= link_to "https://github.com/osabebe", target: :_blank do %>
        <%= image_tag 'https://img.icons8.com/windows/32/000000/github.png' %>
      <% end %>
    </div>
    <div class="footer_name">©︎ 2020 AmiOsabe</div>
  </footer>
</div>

app/views/articles/new.html.erb
<%= form_for(@article, :url => { controller:'articles', action:'create'})do |f| %>
  <%= f.label :画像 %>
  <%= f.file_field :image %>
  <br>
  <%= f.label :URL %>
  <%= f.text_field :site_url,size: 140 %>
  <br>
  <%= f.label :書いた日 %>
  <%= f.text_field :date,size: 140 %>
  <br>
  <%= f.submit %>
  <br>
<% end %>

app/views/contacts/index.html.erb
<div>
  <div class="message_title">Message</div>
  <% @contacts.each do |t| %>
    <div class="contact_index">
      <div class="time"><%= t.created_at %></div>
      <div>お名前：<%= t.name %></div>
      <div>ご連絡先：<%= t.email %></div><br>
      <div class="messages">
        お問い合わせ内容：<%= simple_format(t.content) %>
      </div>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="contact_title">Contact</div>
<%= form_for(@contact, :url => { controller:'contacts', action:'create'})do |f| %>
  <div class="contact">
    <%= f.label :お名前（任意） %><br>
    <%= f.text_field :name,size: 80, class:"input_field" %>
    <br>
    <%= f.label :メールアドレス（任意） %><br>
    <%= f.text_field :email,size: 80, class:"input_field" %>
    <br>
    <%= f.label :お問い合わせ内容 %><br>
    <%= f.text_area :content,size: 80, class:"input_area" %>
    <br>
    <%= f.submit "送信", class:"submit" %>
    <br>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmiOsabe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="body">
      <header class="header">
        <div class="title">ami</div>
        <div>
        <% if user_signed_in? %>
          <% if current_user == @user || current_user.admin? %>
          <span class="border"><%= link_to "Message", contacts_path, class:"link" %>/</span>
          <% end %>
        <% end %>
        <span class="border"><%= link_to "Top", tops_path, class:"link" %>/</span>
        <span class="border"><%= link_to "Products", products_path, class:"link" %>/</span>
        <span class="border"><%= link_to "Articles", articles_path, class:"link" %>/</span>
        <span class="border"><%= link_to "Profile", profiles_path, class:"link" %>/</span>
        <span><%= link_to "Contact", new_contact_path, class:"link" %></span>
        </div>
      </header>
      <%= yield %>
    </div>
  </body>
  
</html>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
   <%= f.label :作品名 %>
   <%= f.text_field :name,size: 140 %>
   <br>
   <%= f.label :制作期間 %>
   <%= f.text_field :production_period,size: 140 %>
   <br>
   <%= f.label :この作品について %>
   <%= f.text_area :detail,size: 140 %>
   <br>
   <%= f.label :使用言語 %>
   <%= f.text_field :language,size: 140 %>
   <br>
   <%= f.label :画像 %>
   <%= f.file_field :image %>
   <br>
   <%= f.label :サイトURL %>
   <%= f.text_field :site_url,size: 140 %>
   <br>
   <%= f.label :GitHubURL %>
   <%= f.text_field :github_url,size: 140 %>
   <br>
   <%= f.submit %>
   <br>
<% end %>

app/views/products/index.html.erb
<div>
  <% if user_signed_in? %>
    <% if current_user == @user || current_user.admin? %>
      <%= link_to "新規投稿へ", new_product_path %>
      <% @products.each do |t| %>
        <%= link_to "編集する", edit_product_path(t.id) %>
       <% end %>
    <% end %>
  <% end %>
  <div class="product_title">Products</div>
    <% @products.each do |t| %>
      <div class="product">
        <div class="content">
          <div class="product_name"><%= t.name %></div><br>
          <div>制作期間：<%= t.production_period %></div>
          <div><%= simple_format(t.detail) %></div><br>
          <div><%= t.language %></div>
        </div>
        <div class="content">
         <%= image_tag t.image_url, class:'product-image' %><br>
         <%= link_to "作品ページへ", t.site_url, target: :_blank, class:'window' %>
         <%= link_to "GitHubへ", t.github_url, target: :_blank, class:'git' %>
        </div>
      </div>
    <% end %>
  </div>
  <footer>
    <div class="my_link">
      <%= link_to "https://www.instagram.com/bebeko___/", target: :_blank do %>
        <%= image_tag 'instagram.png', class:"image" %>
      <% end %>
      <%= link_to "https://www.facebook.com/ami.osabe.9/", target: :_blank do %>
        <%= image_tag 'facebook.png', class:"image" %>
      <% end %>
      <%= link_to "https://github.com/osabebe", target: :_blank do %>
        <%= image_tag 'https://img.icons8.com/windows/32/000000/github.png' %>
      <% end %>
    </div>
    <div class="footer_name">©︎ 2020 AmiOsabe</div>
  </footer>
</div>

app/views/products/new.html.erb
<%= form_for(@product, :url => { controller:'products', action:'create'})do |f| %>
<%= f.label :作品名 %>
<%= f.text_field :name,size: 140 %>
<br>
<%= f.label :制作期間 %>
<%= f.text_field :production_period,size: 140 %>
<br>
<%= f.label :この作品について %>
<%= f.text_area :detail,size: 140 %>
<br>
<%= f.label :使用言語 %>
<%= f.text_field :language,size: 140 %>
<br>
<%= f.label :画像 %>
<%= f.file_field :image %>
<br>
<%= f.label :サイトURL %>
<%= f.text_field :site_url,size: 140 %>
<br>
<%= f.label :GitHubURL %>
<%= f.text_field :github_url,size: 140 %>
<br>
<%= f.submit %>
<br>
<% end %>
<a href="https://icons8.com/icon/16318/github">GitHub icon by Icons8</a>

app/views/profiles/edit.html.erb
<%= form_for @profile do |f| %>
   <br>
   <%= f.label :名前 %>
   <%= f.text_field :name_jp,size: 140 %>
   <br>
   <%= f.label :name %>
   <%= f.text_field :name_en,size: 140 %>
   <br>
   <%= f.label :趣味 %>
   <%= f.text_field :hobby,size: 140 %>
   <br>
   <%= f.label :特技 %>
   <%= f.text_field :strong_point,size: 140 %>
   <br>
   <%= f.label :プロフィール画像 %>
   <%= f.file_field :image %>
   <br>
   <%= f.label :経歴 %>
   <%= f.text_area :career,size: 140 %>
   <br>
   <%= f.label :生年月日 %>
   <%= f.text_field :birthday,size: 140 %>
   <br>
   <%= f.label :自己PR %>
   <%= f.text_area :public_relations,size: 140 %>
   <br>
   <%= f.label :習得言語 %>
   <%= f.text_area :language,size: 140 %>
   <br>
   <%= f.label :習得フレームワーク %>
   <%= f.text_area :framework,size: 140 %>
   <br>
   <%= f.label :デプロイ %>
   <%= f.text_area :deploy,size: 140 %>
   <br>
   <%= f.label :GitHubアカウント %>
   <%= f.text_field :github_url,size: 140 %>
   <br>
   <%= f.label :Instagramアカウント %>
   <%= f.text_field :instagram_url,size: 140 %>
   <br>
   <%= f.label :email %>
   <%= f.text_field :email,size: 140 %>
   <br>
   <%= f.submit "編集する" %>
   <br>
<% end %>

app/views/profiles/index.html.erb
  <% if user_signed_in? %>
    <% if current_user == @user || current_user.admin? %>
      <%= link_to "新規投稿へ", new_profile_path %>
      <% @profiles.each do |t| %>
       <%= link_to "編集する", edit_profile_path(t.id) %>
      <% end %>
    <% end %>
  <% end %>
<div class="profile_title">Profile</div>
  <% @profiles.each do |t| %>
    <div class="profile">
      <div class="photo_name">
        <%= image_tag t.image_url, class:'profile-image' %><br>
        <div class="my-info">
          <div class="name">
            <div class="jp_name"><%= t.name_jp %></div>
            <div class="en_name"><%= t.name_en %></div>
          </div>
          <div class="info">
            <div>誕生日：<%= t.birthday %></div>
            <div>趣味：<%= t.hobby %></div>
            <div>特技：<%= t.strong_point %></div>
            <div>e-mail：<%= t.email %></div>
          </div>
        </div>
      </div>
      <div class="public_relations">
        <%= simple_format(t.public_relations) %><br>
      </div>
      <div class="index">History</div>
      <div class="text"><%= simple_format(t.career) %></div><br>
      <div class="index">Skill（理解度）</div>
      <div class="skill">Language</div>
      <div class="skill_text"><%= simple_format(t.language) %></div><br>
      <div class="skill">Framework</div>
      <div class="skill_text_frame"><%= simple_format(t.framework) %></div><br>
      <div class="skill">Other</div>
      <div class="skill_text_other"><%= simple_format(t.deploy) %></div><br>
    </div>
  <% end %>
  <footer>
    <div class="my_link">
      <%= link_to "https://www.instagram.com/bebeko___/", target: :_blank do %>
        <%= image_tag 'instagram.png', class:"image" %>
      <% end %>
      <%= link_to "https://www.facebook.com/ami.osabe.9/", target: :_blank do %>
        <%= image_tag 'facebook.png', class:"image" %>
      <% end %>
      <%= link_to "https://github.com/osabebe", target: :_blank do %>
        <%= image_tag 'https://img.icons8.com/windows/32/000000/github.png' %>
      <% end %>
    </div>
    <div class="footer_name">©︎ 2020 AmiOsabe</div>
  </footer>

app/views/profiles/new.html.erb
<%= form_for(@profile, :url => { controller:'profiles', action:'create'})do |f| %>
   <br>
   <%= f.label :名前 %>
   <%= f.text_field :name_jp,size: 140 %>
   <br>
   <%= f.label :name %>
   <%= f.text_field :name_en,size: 140 %>
   <br>
   <%= f.label :趣味 %>
   <%= f.text_field :hobby,size: 140 %>
   <br>
   <%= f.label :特技 %>
   <%= f.text_field :strong_point,size: 140 %>
   <br>
   <%= f.label :プロフィール画像 %>
   <%= f.file_field :image %>
   <br>
   <%= f.label :経歴 %>
   <%= f.text_area :career,size: 140 %>
   <br>
   <%= f.label :生年月日 %>
   <%= f.text_field :birthday,size: 140 %>
   <br>
   <%= f.label :自己PR %>
   <%= f.text_area :public_relations,size: 140 %>
   <br>
   <%= f.label :習得言語 %>
   <%= f.text_area :language,size: 140 %>
   <br>
   <%= f.label :習得フレームワーク %>
   <%= f.text_area :framework,size: 140 %>
   <br>
   <%= f.label :デプロイ %>
   <%= f.text_area :deploy,size: 140 %>
   <br>
   <%= f.label :GitHubアカウント %>
   <%= f.text_field :github_url,size: 140 %>
   <br>
   <%= f.label :Instagramアカウント %>
   <%= f.text_field :instagram_url,size: 140 %>
   <br>
   <%= f.label :email %>
   <%= f.text_field :email,size: 140 %>
   <br>
   <%= f.submit %>
   <br>
<% end %>

app/views/tops/edit.html.erb
<%= form_for @top do |f| %>
  <%= f.label :ニュース %>
  <%= f.text_area :news,size: 140 %>
  <br>
  <%= f.label :自己紹介 %>
  <%= f.text_area :introduction,size: 140 %>
  <br>
  <%= f.submit %>
  <br>
<% end %>

app/views/tops/index.html.erb
<div>
  <% if user_signed_in? %>
    <% if current_user == @user || current_user.admin? %>
      <%= link_to "新規投稿へ", new_top_path %>
      <% @tops.each do |t| %>
        <%= link_to "編集する", edit_top_path(t.id) %>
       <% end %>
    <% end %>
  <% end %>
  <% @tops.each do |t| %>
      <div class="news">
        <div class="news_title">News</div>
        <div><%= simple_format(t.news) %></div>
      </div>
      <div class="introduction">
       <%= simple_format(t.introduction) %>
      </div>
  <% end %>
</div>
<footer>
    <div class="my_link">
      <%= link_to "https://www.instagram.com/bebeko___/", target: :_blank do %>
        <%= image_tag 'instagram.png', class:"image" %>
      <% end %>
      <%= link_to "https://www.facebook.com/ami.osabe.9/", target: :_blank do %>
        <%= image_tag 'facebook.png', class:"image" %>
      <% end %>
      <%= link_to "https://github.com/osabebe", target: :_blank do %>
        <%= image_tag 'https://img.icons8.com/windows/32/000000/github.png' %>
      <% end %>
    </div>
    <div class="footer_name">©︎ 2020 AmiOsabe</div>
  </footer>

app/views/tops/new.html.erb
<%= form_for(@top, :url => { controller:'tops', action:'create'})do |f| %>
  <%= f.label :ニュース %>
  <%= f.text_area :news,size: 140 %>
  <br>
  <%= f.label :自己紹介 %>
  <%= f.text_area :introduction,size: 140 %>
  <br>
  <%= f.submit %>
  <br>
<% end %>